"""Security-headers contract test.

Sibling of `test_error_envelope_contract.py` — that one pins error
body shape, this pins response *headers*. If the security middleware
gets accidentally dropped during a future refactor, the next pen test
surfaces the gap months later. This test catches it at PR time.

What we pin
-----------
Every response carries:
  * `X-Content-Type-Options: nosniff`
  * `X-Frame-Options: DENY`
  * `Referrer-Policy: strict-origin-when-cross-origin`
  * `Content-Security-Policy: default-src 'none'; frame-ancestors 'none'`
  * `Permissions-Policy: …`

In production mode (`AEC_ENV=production`), additionally:
  * `Strict-Transport-Security: max-age=63072000; includeSubDomains; preload`

The test imports the canonical header values from the middleware
module rather than hard-coding them, so a future tightening (e.g.
adding `report-to` to CSP) flows through without touching the test.

Why test across multiple status codes
-------------------------------------
Middleware ordering bugs are subtle: a 404 generated by Starlette
itself (no route match) goes through a different code path than a
404 raised by a handler, which goes through a different path than
a 200 OK. We hit one of each so a regression on the "Starlette
generates the response" branch can't slip through.
"""

from __future__ import annotations

from collections.abc import AsyncIterator, Iterator

import pytest
from fastapi import FastAPI, HTTPException
from fastapi.exceptions import RequestValidationError
from httpx import ASGITransport, AsyncClient

from middleware.security_headers import (
    HSTS_HEADER_VALUE,
    STATIC_SECURITY_HEADERS,
    SecurityHeadersMiddleware,
)

pytestmark = pytest.mark.asyncio


def _build_app(*, production: bool, with_routers: bool = True) -> FastAPI:
    """Build a test app with the same handler + middleware wiring as
    `main.py`, parametrised on the `production` flag.

    `with_routers=False` builds an app with no routers mounted, so
    we can hit a path that has no matching route and exercises the
    Starlette-generated 404 path.
    """
    from core.envelope import (
        http_exception_handler,
        unhandled_exception_handler,
        validation_exception_handler,
    )

    app = FastAPI()
    app.add_middleware(SecurityHeadersMiddleware, production=production)
    app.add_exception_handler(HTTPException, http_exception_handler)
    app.add_exception_handler(RequestValidationError, validation_exception_handler)
    app.add_exception_handler(Exception, unhandled_exception_handler)
    if with_routers:
        from routers import pulse as pulse_router

        app.include_router(pulse_router.router)
    return app


def _assert_static_headers(response_headers, *, context: str) -> None:
    """Assert every static header is present with the canonical value.

    Centralised so test failures surface the offending header by name
    rather than dumping the whole headers map.
    """
    for name, expected in STATIC_SECURITY_HEADERS.items():
        actual = response_headers.get(name)
        assert actual == expected, (
            f"{context}: expected `{name}: {expected}`, got `{actual!r}`. "
            "If this is intentional (e.g. a route legitimately needs a "
            "looser CSP for an embedded asset), set the header in the "
            "route handler — `setdefault` semantics in the middleware "
            "preserve route-level overrides."
        )


# ---------- Static headers across status codes ----------


@pytest.fixture
async def app_dev(fake_auth, fake_db) -> Iterator[FastAPI]:
    """Dev-mode app (no HSTS) with the pulse router mounted."""
    from db.deps import get_db
    from middleware.auth import require_auth

    async def _override_db() -> AsyncIterator:
        yield fake_db

    app = _build_app(production=False)
    app.dependency_overrides[require_auth] = lambda: fake_auth
    app.dependency_overrides[get_db] = _override_db
    try:
        yield app
    finally:
        app.dependency_overrides.clear()


@pytest.fixture
async def client_dev(app_dev: FastAPI) -> AsyncIterator[AsyncClient]:
    transport = ASGITransport(app=app_dev, raise_app_exceptions=False)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        yield ac


async def test_static_headers_present_on_200(client_dev):
    """200 OK — the happy-path response. Every header must be there."""
    res = await client_dev.get("/api/v1/pulse/tasks")
    assert res.status_code == 200
    _assert_static_headers(res.headers, context="200 OK")


async def test_static_headers_present_on_handler_raised_404(client_dev):
    """404 raised by a handler (`HTTPException(404)`) — goes through
    `http_exception_handler`. Headers must be on that response too —
    a regression that wired security headers via a per-route decorator
    would fire on 200s but miss this path."""
    from uuid import uuid4

    res = await client_dev.get(f"/api/v1/pulse/projects/{uuid4()}/dashboard")
    # The dashboard route returns 200 with empty data when no rows
    # exist; we want a real 404 from the by-id route.
    # Pulse exposes `/projects/{id}/dashboard` and `/tasks/{id}` —
    # the dashboard 200s on empty inputs, but `/tasks/{id}` 404s when
    # the FakeAsyncSession.get returns None.
    # … so just hit a route that 405s instead (simpler reliable
    # negative).
    res = await client_dev.put("/api/v1/pulse/tasks")  # GET-only path
    assert res.status_code == 405
    _assert_static_headers(res.headers, context="405 Method Not Allowed")


async def test_static_headers_present_on_starlette_generated_404():
    """Starlette generates the 404 directly (no handler matches the
    path at all). Different code path inside Starlette than a
    handler-raised 404 — pin separately so a middleware ordering
    regression that misses the no-route path can't ship.
    """
    app = _build_app(production=False, with_routers=False)
    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        res = await ac.get("/no-such-path-anywhere")
    assert res.status_code == 404
    _assert_static_headers(res.headers, context="Starlette 404")


# ---------- HSTS conditional ----------


async def test_hsts_present_only_in_production_mode():
    """Two apps, two assertions:
    * `production=False` → no HSTS (local dev runs over HTTP and
      emitting HSTS there pins the developer's browser to HTTPS,
      breaking the localhost loop).
    * `production=True`  → HSTS with the canonical value.
    """
    # Dev: NOT present.
    dev_app = _build_app(production=False, with_routers=False)
    transport = ASGITransport(app=dev_app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        res = await ac.get("/no-such-path")
    assert "Strict-Transport-Security" not in res.headers, (
        "HSTS leaked into a dev-mode response. Local dev over HTTP "
        "would brick the developer's browser; the middleware MUST "
        "gate HSTS behind `production=True`."
    )

    # Prod: present with the canonical value.
    prod_app = _build_app(production=True, with_routers=False)
    transport = ASGITransport(app=prod_app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        res = await ac.get("/no-such-path")
    assert res.headers.get("Strict-Transport-Security") == HSTS_HEADER_VALUE, (
        f"Expected HSTS=`{HSTS_HEADER_VALUE}`, got `{res.headers.get('Strict-Transport-Security')!r}`."
    )


# ---------- Override-ability ----------


async def test_route_set_header_is_not_clobbered_by_middleware():
    """`setdefault` semantics: a route that legitimately needs a
    looser CSP (e.g. a future PDF preview that inlines styles) can
    set its own `Content-Security-Policy` header in the response, and
    the middleware MUST preserve it.

    Regression shape: middleware uses `__setitem__` instead of
    `setdefault`, clobbering the route's value back to the default.
    Pin it.
    """
    from fastapi import FastAPI as _FastAPI
    from fastapi.responses import JSONResponse

    app = _FastAPI()
    app.add_middleware(SecurityHeadersMiddleware, production=False)

    @app.get("/special")
    def _special() -> JSONResponse:
        return JSONResponse(
            {"ok": True},
            headers={"Content-Security-Policy": "default-src 'self'"},
        )

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as ac:
        res = await ac.get("/special")
    assert res.headers["Content-Security-Policy"] == "default-src 'self'", (
        "Middleware clobbered a route-set CSP header. Use `setdefault` "
        "(not `__setitem__`) so explicit per-route overrides win."
    )
    # The non-CSP headers still get added — only the route-set one is preserved.
    assert res.headers.get("X-Frame-Options") == "DENY"
