import Link from "next/link";
import { Code2, Key, ShieldCheck, Zap } from "lucide-react";


/**
 * Developer docs for the public REST API.
 *
 * Static (server-rendered) — no client state. The authoritative
 * source for the constants here is:
 *   * `apps/api/services/api_keys.py` — SCOPES + DEFAULT_RATE_LIMIT_PER_MINUTE
 *   * `apps/api/middleware/api_key_auth.py` — the dual-auth dependency
 *   * The OpenAPI spec at `/openapi.json` (auto-generated by FastAPI)
 *
 * If scope vocabulary changes, hand-edit the table. The auto-generated
 * OpenAPI link below stays correct without intervention because FastAPI
 * derives it from the route signatures.
 */
export default function ApiDocsPage() {
  return (
    <div className="prose prose-slate max-w-none space-y-10 text-sm">
      {/* ---------- Header ---------- */}
      <header className="not-prose space-y-2">
        <div className="flex items-center gap-2">
          <Code2 size={20} className="text-blue-600" />
          <h1 className="text-2xl font-bold text-slate-900">API documentation</h1>
        </div>
        <p className="text-sm text-slate-600">
          REST API for tích hợp hệ thống của khách hàng (CRM, ERP, ETL pipeline)
          với AEC Platform. Authenticated by per-org API keys. Rate-limited per
          key via Redis token bucket.
        </p>
        <p className="text-xs text-slate-500">
          Quản lý keys:{" "}
          <Link
            href="/settings/api-keys"
            className="font-medium text-blue-600 hover:underline"
          >
            /settings/api-keys
          </Link>
          {" · "}
          OpenAPI spec:{" "}
          <a
            href="/openapi.json"
            className="font-medium text-blue-600 hover:underline"
          >
            /openapi.json
          </a>
        </p>
      </header>

      {/* ---------- TL;DR ---------- */}
      <section className="not-prose rounded-xl border border-blue-200 bg-blue-50 p-4">
        <h2 className="text-sm font-semibold text-blue-900">Tóm tắt</h2>
        <ol className="mt-2 list-decimal space-y-1 pl-5 text-xs text-blue-900">
          <li>
            Tạo key tại <code>/settings/api-keys</code> — copy plaintext xuất hiện
            đúng một lần.
          </li>
          <li>
            Gửi mọi request với header{" "}
            <code>Authorization: Bearer aec_…</code>. Không cần
            <code>X-Org-ID</code> — tổ chức được suy ra từ key.
          </li>
          <li>
            Mỗi key có rate limit (mặc định 60 req/phút). Vượt → 429 với
            <code>Retry-After</code>.
          </li>
          <li>
            Scopes (<code>projects:read</code>, <code>defects:write</code>,
            …) bảo vệ từng endpoint. Thiếu scope → 403 với{" "}
            <code>missing_scope: …</code>.
          </li>
        </ol>
      </section>

      {/* ---------- Authentication ---------- */}
      <section>
        <h2 id="auth" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          <Key size={16} className="mr-1 inline align-text-top text-slate-500" />
          Authentication
        </h2>
        <p className="text-sm text-slate-600">
          Mọi request gắn header <code>Authorization: Bearer &lt;key&gt;</code>.
          Key luôn có dạng <code>aec_</code> + 64 ký tự hex. Server hash bằng
          SHA-256 và lookup; key plaintext không bao giờ được lưu hoặc log.
        </p>
        <div className="not-prose mt-3 overflow-x-auto rounded-lg bg-slate-900 p-4 text-xs text-slate-100">
          <pre className="font-mono">
            <code>{`# Liệt kê dự án
curl https://api.aec-platform.vn/api/v1/projects \\
  -H "Authorization: Bearer aec_a1b2c3d4e5f6abcdef1234567890abcdef1234567890abcdef1234567890ab"`}</code>
          </pre>
        </div>
        <p className="mt-3 text-xs text-slate-500">
          Nếu key sai/đã revoke/đã hết hạn → <code>401 Invalid API key</code>.
          Token người dùng (Supabase JWT) cũng được hỗ trợ trên cùng endpoint;
          nhưng JWT cần kèm header <code>X-Org-ID</code>, còn API key thì không.
        </p>
      </section>

      {/* ---------- Rate limiting ---------- */}
      <section>
        <h2 id="rate-limit" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          <Zap size={16} className="mr-1 inline align-text-top text-slate-500" />
          Rate limiting
        </h2>
        <p className="text-sm text-slate-600">
          Mỗi key có một token bucket trong Redis, tính theo phút (UTC). Mặc
          định 60 request/phút; admin có thể nâng riêng cho từng key tới 10.000
          rpm cho đối tác cao tải. Vượt giới hạn → <code>429 rate_limit_exceeded</code>{" "}
          kèm header <code>Retry-After</code> (giây tới phút kế tiếp).
        </p>
        <div className="not-prose mt-3 overflow-x-auto rounded-lg border border-slate-200">
          <table className="w-full text-xs">
            <thead className="bg-slate-50 text-left text-[11px] uppercase text-slate-500">
              <tr>
                <th className="px-3 py-2">Response</th>
                <th className="px-3 py-2">Header</th>
                <th className="px-3 py-2">Mục đích</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              <tr>
                <td className="px-3 py-2 font-mono">429</td>
                <td className="px-3 py-2 font-mono">Retry-After: 38</td>
                <td className="px-3 py-2">
                  Số giây client nên chờ trước khi gửi lại — đủ để bucket
                  rollover sang phút mới.
                </td>
              </tr>
              <tr>
                <td className="px-3 py-2 font-mono">2xx</td>
                <td className="px-3 py-2 text-slate-400">(none)</td>
                <td className="px-3 py-2">
                  Hiện chưa expose <code>X-RateLimit-*</code> headers; lập kế
                  hoạch cho phiên bản sau.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ---------- Scopes ---------- */}
      <section>
        <h2 id="scopes" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          <ShieldCheck size={16} className="mr-1 inline align-text-top text-slate-500" />
          Scopes
        </h2>
        <p className="text-sm text-slate-600">
          Mỗi key có một tập <em>scopes</em> dạng{" "}
          <code>&lt;domain&gt;:&lt;action&gt;</code>. Endpoint khai báo scope nó cần;
          thiếu scope → <code>403 missing_scope: &lt;tên&gt;</code>. Scope{" "}
          <code>*</code> bypass mọi check (chỉ dùng cho ops script một lần).
        </p>
        <div className="not-prose mt-3 overflow-x-auto rounded-lg border border-slate-200">
          <table className="w-full text-xs">
            <thead className="bg-slate-50 text-left text-[11px] uppercase text-slate-500">
              <tr>
                <th className="px-3 py-2">Domain</th>
                <th className="px-3 py-2">Read</th>
                <th className="px-3 py-2">Write</th>
                <th className="px-3 py-2">Mô tả</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {SCOPE_DOC.map((row) => (
                <tr key={row.domain}>
                  <td className="px-3 py-2 font-mono">{row.domain}</td>
                  <td className="px-3 py-2 font-mono text-slate-500">
                    {row.read ? `${row.domain}:read` : "—"}
                  </td>
                  <td className="px-3 py-2 font-mono text-slate-500">
                    {row.write ? `${row.domain}:${row.writeAction}` : "—"}
                  </td>
                  <td className="px-3 py-2 text-slate-600">{row.description}</td>
                </tr>
              ))}
              <tr className="bg-rose-50/40">
                <td className="px-3 py-2 font-mono text-rose-800">*</td>
                <td className="px-3 py-2" />
                <td className="px-3 py-2" />
                <td className="px-3 py-2 text-rose-800">
                  Toàn quyền tổ chức. Tránh dùng cho tích hợp lâu dài.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ---------- Errors ---------- */}
      <section>
        <h2 id="errors" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          Error responses
        </h2>
        <p className="text-sm text-slate-600">
          Mọi lỗi trả về JSON envelope chuẩn của platform (
          <code>{`{ "data": null, "errors": [{ "message": "…" }] }`}</code>).
          Status codes:
        </p>
        <div className="not-prose mt-3 overflow-x-auto rounded-lg border border-slate-200">
          <table className="w-full text-xs">
            <thead className="bg-slate-50 text-left text-[11px] uppercase text-slate-500">
              <tr>
                <th className="px-3 py-2">Status</th>
                <th className="px-3 py-2">Khi nào</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              <tr>
                <td className="px-3 py-2 font-mono">401</td>
                <td className="px-3 py-2">
                  Header <code>Authorization</code> thiếu, sai format, hoặc key
                  không tồn tại / đã revoke / đã hết hạn.
                </td>
              </tr>
              <tr>
                <td className="px-3 py-2 font-mono">403</td>
                <td className="px-3 py-2">
                  Key thiếu scope cần thiết. Body chứa{" "}
                  <code>missing_scope: &lt;tên&gt;</code>.
                </td>
              </tr>
              <tr>
                <td className="px-3 py-2 font-mono">429</td>
                <td className="px-3 py-2">
                  Rate limit. Đọc <code>Retry-After</code> header.
                </td>
              </tr>
              <tr>
                <td className="px-3 py-2 font-mono">4xx khác</td>
                <td className="px-3 py-2">
                  Lỗi validation, resource not found, v.v. Body có thông điệp
                  cụ thể.
                </td>
              </tr>
              <tr>
                <td className="px-3 py-2 font-mono">5xx</td>
                <td className="px-3 py-2">
                  Lỗi server. Tự retry với exponential backoff (xem snippet bên
                  dưới).
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ---------- Code samples ---------- */}
      <section>
        <h2 id="samples" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          Code samples
        </h2>

        <h3 className="not-prose mt-4 text-sm font-semibold text-slate-700">
          TypeScript / Node
        </h3>
        <div className="not-prose mt-2 overflow-x-auto rounded-lg bg-slate-900 p-4 text-xs text-slate-100">
          <pre className="font-mono">
            <code>{`// Minimal: list projects
const res = await fetch("https://api.aec-platform.vn/api/v1/projects", {
  headers: {
    Authorization: \`Bearer \${process.env.AEC_API_KEY}\`,
  },
});
if (res.status === 429) {
  const retryAfter = Number(res.headers.get("retry-after") ?? "60");
  await new Promise(r => setTimeout(r, retryAfter * 1000));
  // …retry
}
const { data } = await res.json();`}</code>
          </pre>
        </div>

        <h3 className="not-prose mt-6 text-sm font-semibold text-slate-700">
          Python
        </h3>
        <div className="not-prose mt-2 overflow-x-auto rounded-lg bg-slate-900 p-4 text-xs text-slate-100">
          <pre className="font-mono">
            <code>{`import os
import time
import httpx

API_KEY = os.environ["AEC_API_KEY"]
BASE = "https://api.aec-platform.vn"

def call(path: str, **kw):
    """Tự động retry trên 429 + 5xx (jittered exponential backoff)."""
    delay = 1.0
    for attempt in range(5):
        res = httpx.get(f"{BASE}{path}",
                        headers={"Authorization": f"Bearer {API_KEY}"},
                        **kw)
        if res.status_code == 429:
            time.sleep(int(res.headers.get("retry-after", "60")))
            continue
        if 500 <= res.status_code < 600:
            time.sleep(delay)
            delay *= 2
            continue
        res.raise_for_status()
        return res.json()["data"]
    raise RuntimeError("exhausted retries")`}</code>
          </pre>
        </div>

        <h3 className="not-prose mt-6 text-sm font-semibold text-slate-700">
          Go
        </h3>
        <div className="not-prose mt-2 overflow-x-auto rounded-lg bg-slate-900 p-4 text-xs text-slate-100">
          <pre className="font-mono">
            <code>{`package main

import (
    "fmt"
    "io"
    "net/http"
    "os"
    "strconv"
    "time"
)

func call(path string) ([]byte, error) {
    base := "https://api.aec-platform.vn"
    key := os.Getenv("AEC_API_KEY")
    delay := time.Second
    for attempt := 0; attempt < 5; attempt++ {
        req, _ := http.NewRequest("GET", base+path, nil)
        req.Header.Set("Authorization", "Bearer "+key)
        res, err := http.DefaultClient.Do(req)
        if err != nil {
            return nil, err
        }
        defer res.Body.Close()
        if res.StatusCode == 429 {
            secs, _ := strconv.Atoi(res.Header.Get("Retry-After"))
            time.Sleep(time.Duration(secs) * time.Second)
            continue
        }
        if res.StatusCode >= 500 {
            time.Sleep(delay)
            delay *= 2
            continue
        }
        if res.StatusCode >= 400 {
            return nil, fmt.Errorf("status %d", res.StatusCode)
        }
        return io.ReadAll(res.Body)
    }
    return nil, fmt.Errorf("exhausted retries")
}`}</code>
          </pre>
        </div>
      </section>

      {/* ---------- Best practices ---------- */}
      <section>
        <h2 id="best-practices" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          Best practices
        </h2>
        <ul className="space-y-1.5 text-sm text-slate-700">
          <li>
            <strong>Một key cho một mục đích.</strong> CRM-sync và ETL-export là
            hai tích hợp khác nhau → hai key. Revoke một cái không kéo cái kia
            xuống.
          </li>
          <li>
            <strong>Scope tối thiểu.</strong> Read-only ETL pipeline → chỉ{" "}
            <code>projects:read</code>, không cấp <code>:write</code>. Một key bị
            lộ thì hậu quả bị giới hạn.
          </li>
          <li>
            <strong>Đặt expires_at cho key thử nghiệm.</strong> Demo / vendor
            POC nên có hạn 30 ngày. Tránh quên revoke.
          </li>
          <li>
            <strong>Lưu trong vault, không trong repo.</strong> AWS Secrets
            Manager / GCP Secret Manager / Vault — không commit vào git, không
            in ra log.
          </li>
          <li>
            <strong>Theo dõi <code>last_used_at</code>.</strong> Trang{" "}
            <Link href="/settings/api-keys" className="text-blue-600 hover:underline">
              /settings/api-keys
            </Link>{" "}
            hiển thị lần dùng cuối — key không dùng 90 ngày là ứng viên revoke.
          </li>
        </ul>
      </section>
    </div>
  );
}


// Source-of-truth mirror of `services.api_keys.SCOPES`. Hand-maintained
// because this is documentation; the compiler can't catch drift.
const SCOPE_DOC: Array<{
  domain: string;
  read: boolean;
  write: boolean;
  writeAction: "write" | "admin";
  description: string;
}> = [
  {
    domain: "projects",
    read: true,
    write: true,
    writeAction: "write",
    description: "Dự án — danh sách, chi tiết, tạo/sửa.",
  },
  {
    domain: "defects",
    read: true,
    write: true,
    writeAction: "write",
    description: "Lỗi (snag list) từ Handover module.",
  },
  {
    domain: "rfis",
    read: true,
    write: true,
    writeAction: "write",
    description: "Yêu cầu làm rõ (Request For Information).",
  },
  {
    domain: "change_orders",
    read: true,
    write: true,
    writeAction: "write",
    description: "Yêu cầu thay đổi thi công.",
  },
  {
    domain: "suppliers",
    read: true,
    write: true,
    writeAction: "write",
    description: "Sổ tay nhà cung cấp.",
  },
  {
    domain: "estimates",
    read: true,
    write: true,
    writeAction: "write",
    description: "Dự toán CostPulse.",
  },
  {
    domain: "webhooks",
    read: false,
    write: true,
    writeAction: "admin",
    description: "Quản lý webhook subscriptions (admin-only).",
  },
  {
    domain: "audit",
    read: true,
    write: false,
    writeAction: "write",
    description: "Nhật ký kiểm tra (read-only).",
  },
  {
    domain: "search",
    read: true,
    write: false,
    writeAction: "write",
    description: "Cross-module search endpoint.",
  },
];
