import Link from "next/link";
import { Code2, Key, ShieldCheck, Zap } from "lucide-react";

import { TranslationNotice } from "../_components/TranslationNotice";


/**
 * Developer docs for the public REST API.
 *
 * Static (server-rendered) — no client state. The authoritative
 * source for the constants here is:
 *   * `apps/api/services/api_keys.py` — SCOPES + DEFAULT_RATE_LIMIT_PER_MINUTE
 *   * `apps/api/middleware/api_key_auth.py` — the dual-auth dependency
 *   * The OpenAPI spec at `/openapi.json` (auto-generated by FastAPI)
 *
 * Body content is currently Vietnamese-canonical with EN translation
 * in progress (see `<TranslationNotice>`). The `/docs` index +
 * `/docs/webhooks/events` are fully i18n'd; this page's 600+ line
 * string surface lands incrementally rather than blocking the cycle.
 */
export default function ApiDocsPage() {
  return (
    <div className="prose prose-slate max-w-none space-y-10 text-sm">
      <TranslationNotice />
      {/* ---------- Header ---------- */}
      <header className="not-prose space-y-2">
        <div className="flex items-center gap-2">
          <Code2 size={20} className="text-blue-600" />
          <h1 className="text-2xl font-bold text-slate-900">API documentation</h1>
        </div>
        <p className="text-sm text-slate-600">
          REST API for tích hợp hệ thống của khách hàng (CRM, ERP, ETL pipeline)
          với AEC Platform. Authenticated by per-org API keys. Rate-limited per
          key via Redis token bucket.
        </p>
        <p className="text-xs text-slate-500">
          Quản lý keys:{" "}
          <Link
            href="/settings/api-keys"
            className="font-medium text-blue-600 hover:underline"
          >
            /settings/api-keys
          </Link>
          {" · "}
          OpenAPI spec:{" "}
          <a
            href="/openapi.json"
            className="font-medium text-blue-600 hover:underline"
          >
            /openapi.json
          </a>
        </p>
      </header>

      {/* ---------- TL;DR ---------- */}
      <section className="not-prose rounded-xl border border-blue-200 bg-blue-50 p-4">
        <h2 className="text-sm font-semibold text-blue-900">Tóm tắt</h2>
        <ol className="mt-2 list-decimal space-y-1 pl-5 text-xs text-blue-900">
          <li>
            Tạo key tại <code>/settings/api-keys</code> — copy plaintext xuất hiện
            đúng một lần.
          </li>
          <li>
            Gửi mọi request với header{" "}
            <code>Authorization: Bearer aec_…</code>. Không cần
            <code>X-Org-ID</code> — tổ chức được suy ra từ key.
          </li>
          <li>
            Mỗi key có rate limit (mặc định 60 req/phút). Vượt → 429 với
            <code>Retry-After</code>.
          </li>
          <li>
            Scopes (<code>projects:read</code>, <code>defects:write</code>,
            …) bảo vệ từng endpoint. Thiếu scope → 403 với{" "}
            <code>missing_scope: …</code>.
          </li>
        </ol>
      </section>

      {/* ---------- Authentication ---------- */}
      <section>
        <h2 id="auth" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          <Key size={16} className="mr-1 inline align-text-top text-slate-500" />
          Authentication
        </h2>
        <p className="text-sm text-slate-600">
          Mọi request gắn header <code>Authorization: Bearer &lt;key&gt;</code>.
          Key luôn có dạng <code>aec_</code> + 64 ký tự hex. Server hash bằng
          SHA-256 và lookup; key plaintext không bao giờ được lưu hoặc log.
        </p>
        <div className="not-prose mt-3 overflow-x-auto rounded-lg bg-slate-900 p-4 text-xs text-slate-100">
          <pre className="font-mono">
            <code>{`# Liệt kê dự án
curl https://api.aec-platform.vn/api/v1/projects \\
  -H "Authorization: Bearer aec_a1b2c3d4e5f6abcdef1234567890abcdef1234567890abcdef1234567890ab"`}</code>
          </pre>
        </div>
        <p className="mt-3 text-xs text-slate-500">
          Nếu key sai/đã revoke/đã hết hạn → <code>401 Invalid API key</code>.
          Token người dùng (Supabase JWT) cũng được hỗ trợ trên cùng endpoint;
          nhưng JWT cần kèm header <code>X-Org-ID</code>, còn API key thì không.
        </p>
      </section>

      {/* ---------- Rate limiting ---------- */}
      <section>
        <h2 id="rate-limit" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          <Zap size={16} className="mr-1 inline align-text-top text-slate-500" />
          Rate limiting
        </h2>
        <p className="text-sm text-slate-600">
          Mỗi key có một token bucket trong Redis, tính theo phút (UTC). Mặc
          định 60 request/phút; admin có thể nâng riêng cho từng key tới 10.000
          rpm cho đối tác cao tải. Vượt giới hạn → <code>429 rate_limit_exceeded</code>{" "}
          kèm header <code>Retry-After</code> (giây tới phút kế tiếp).
        </p>
        <div className="not-prose mt-3 overflow-x-auto rounded-lg border border-slate-200">
          <table className="w-full text-xs">
            <thead className="bg-slate-50 text-left text-[11px] uppercase text-slate-500">
              <tr>
                <th className="px-3 py-2">Response</th>
                <th className="px-3 py-2">Header</th>
                <th className="px-3 py-2">Mục đích</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              <tr>
                <td className="px-3 py-2 font-mono">429</td>
                <td className="px-3 py-2 font-mono">Retry-After: 38</td>
                <td className="px-3 py-2">
                  Số giây client nên chờ trước khi gửi lại — đủ để bucket
                  rollover sang phút mới.
                </td>
              </tr>
              <tr>
                <td className="px-3 py-2 font-mono">2xx</td>
                <td className="px-3 py-2 text-slate-400">(none)</td>
                <td className="px-3 py-2">
                  Hiện chưa expose <code>X-RateLimit-*</code> headers; lập kế
                  hoạch cho phiên bản sau.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ---------- Scopes ---------- */}
      <section>
        <h2 id="scopes" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          <ShieldCheck size={16} className="mr-1 inline align-text-top text-slate-500" />
          Scopes
        </h2>
        <p className="text-sm text-slate-600">
          Mỗi key có một tập <em>scopes</em> dạng{" "}
          <code>&lt;domain&gt;:&lt;action&gt;</code>. Endpoint khai báo scope nó cần;
          thiếu scope → <code>403 missing_scope: &lt;tên&gt;</code>. Scope{" "}
          <code>*</code> bypass mọi check (chỉ dùng cho ops script một lần).
        </p>
        <div className="not-prose mt-3 overflow-x-auto rounded-lg border border-slate-200">
          <table className="w-full text-xs">
            <thead className="bg-slate-50 text-left text-[11px] uppercase text-slate-500">
              <tr>
                <th className="px-3 py-2">Domain</th>
                <th className="px-3 py-2">Read</th>
                <th className="px-3 py-2">Write</th>
                <th className="px-3 py-2">Mô tả</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {SCOPE_DOC.map((row) => (
                <tr key={row.domain}>
                  <td className="px-3 py-2 font-mono">{row.domain}</td>
                  <td className="px-3 py-2 font-mono text-slate-500">
                    {row.read ? `${row.domain}:read` : "—"}
                  </td>
                  <td className="px-3 py-2 font-mono text-slate-500">
                    {row.write ? `${row.domain}:${row.writeAction}` : "—"}
                  </td>
                  <td className="px-3 py-2 text-slate-600">{row.description}</td>
                </tr>
              ))}
              <tr className="bg-rose-50/40">
                <td className="px-3 py-2 font-mono text-rose-800">*</td>
                <td className="px-3 py-2" />
                <td className="px-3 py-2" />
                <td className="px-3 py-2 text-rose-800">
                  Toàn quyền tổ chức. Tránh dùng cho tích hợp lâu dài.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ---------- Errors ---------- */}
      <section>
        <h2 id="errors" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          Error responses
        </h2>
        <p className="text-sm text-slate-600">
          Mọi lỗi trả về JSON envelope chuẩn của platform (
          <code>{`{ "data": null, "errors": [{ "message": "…" }] }`}</code>).
          Status codes:
        </p>
        <div className="not-prose mt-3 overflow-x-auto rounded-lg border border-slate-200">
          <table className="w-full text-xs">
            <thead className="bg-slate-50 text-left text-[11px] uppercase text-slate-500">
              <tr>
                <th className="px-3 py-2">Status</th>
                <th className="px-3 py-2">Khi nào</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              <tr>
                <td className="px-3 py-2 font-mono">401</td>
                <td className="px-3 py-2">
                  Header <code>Authorization</code> thiếu, sai format, hoặc key
                  không tồn tại / đã revoke / đã hết hạn.
                </td>
              </tr>
              <tr>
                <td className="px-3 py-2 font-mono">403</td>
                <td className="px-3 py-2">
                  Key thiếu scope cần thiết. Body chứa{" "}
                  <code>missing_scope: &lt;tên&gt;</code>.
                </td>
              </tr>
              <tr>
                <td className="px-3 py-2 font-mono">429</td>
                <td className="px-3 py-2">
                  Rate limit. Đọc <code>Retry-After</code> header.
                </td>
              </tr>
              <tr>
                <td className="px-3 py-2 font-mono">4xx khác</td>
                <td className="px-3 py-2">
                  Lỗi validation, resource not found, v.v. Body có thông điệp
                  cụ thể.
                </td>
              </tr>
              <tr>
                <td className="px-3 py-2 font-mono">5xx</td>
                <td className="px-3 py-2">
                  Lỗi server. Tự retry với exponential backoff (xem snippet bên
                  dưới).
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ---------- Code samples ---------- */}
      <section>
        <h2 id="samples" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          Code samples
        </h2>

        {/* TypeScript SDK first — recommended path for partners
            building on Node / browsers / Cloudflare Workers / Deno.
            The raw-fetch sample below is for partners on stacks the
            SDK doesn't reach (Python, Go) or who prefer hand-rolled
            HTTP. Listing the SDK first surfaces the recommended
            choice without forcing the partner to scroll. */}
        <h3 className="not-prose mt-4 text-sm font-semibold text-slate-700">
          TypeScript SDK (recommended)
        </h3>
        <p className="text-sm text-slate-700">
          <code className="rounded bg-slate-100 px-1">@aec/sdk</code> là
          typed client tự sinh từ OpenAPI. Tự động retry trên 429 + 5xx
          với exponential backoff, unwrap envelope, type-safe trên mọi
          method. CI gate đảm bảo SDK không drift khỏi route signatures —
          mỗi route mới trên server xuất hiện ngay khi bạn{" "}
          <code className="rounded bg-slate-100 px-1">pnpm update</code>.
        </p>
        <div className="not-prose mt-2 overflow-x-auto rounded-lg bg-slate-900 p-4 text-xs text-slate-100">
          <pre className="font-mono">
            <code>{`# Install
pnpm add @aec/sdk      # or: npm install / yarn add

# Use
import { AecClient, AecApiError } from "@aec/sdk";

const client = new AecClient({
  apiKey: process.env.AEC_API_KEY!,
  // Optional. Override for staging / self-hosted.
  // baseUrl: "https://staging-api.aec-platform.vn",
});

try {
  // Method names track FastAPI's operationId. Path params are typed;
  // query params are inferred from the route's Query() declarations.
  const projects = await client.ops.list_projects_api_v1_projects_get(
    {},
    { status: "construction", page: 1 },
  );
  console.log(\`got \${projects?.length ?? 0} projects\`);
} catch (err) {
  if (err instanceof AecApiError) {
    // status + parsed body are on the error so retry / fallback
    // logic can branch without re-parsing.
    if (err.status === 403) console.error("missing scope:", err.message);
    else if (err.status === 429) console.error("rate limited");
    else throw err;
  } else {
    throw err;
  }
}`}</code>
          </pre>
        </div>
        <p className="not-prose mt-2 text-[11px] text-slate-500">
          Source:{" "}
          <code className="rounded bg-slate-100 px-1">packages/sdk/</code>{" "}
          in the monorepo. <code>maxRetries</code>, custom <code>fetch</code>{" "}
          (for undici / polyfills), and per-call timeouts are configurable —
          see the README in the package.
        </p>

        <h3 className="not-prose mt-6 text-sm font-semibold text-slate-700">
          TypeScript / Node (raw fetch)
        </h3>
        <p className="text-sm text-slate-700">
          Use the SDK above when possible. This snippet is for stacks
          that can't add a dependency (edge runtimes with strict bundle
          budgets, vendored client code, etc).
        </p>
        <div className="not-prose mt-2 overflow-x-auto rounded-lg bg-slate-900 p-4 text-xs text-slate-100">
          <pre className="font-mono">
            <code>{`// Minimal: list projects
const res = await fetch("https://api.aec-platform.vn/api/v1/projects", {
  headers: {
    Authorization: \`Bearer \${process.env.AEC_API_KEY}\`,
  },
});
if (res.status === 429) {
  const retryAfter = Number(res.headers.get("retry-after") ?? "60");
  await new Promise(r => setTimeout(r, retryAfter * 1000));
  // …retry
}
const { data } = await res.json();`}</code>
          </pre>
        </div>

        <h3 className="not-prose mt-6 text-sm font-semibold text-slate-700">
          Python
        </h3>
        <div className="not-prose mt-2 overflow-x-auto rounded-lg bg-slate-900 p-4 text-xs text-slate-100">
          <pre className="font-mono">
            <code>{`import os
import time
import httpx

API_KEY = os.environ["AEC_API_KEY"]
BASE = "https://api.aec-platform.vn"

def call(path: str, **kw):
    """Tự động retry trên 429 + 5xx (jittered exponential backoff)."""
    delay = 1.0
    for attempt in range(5):
        res = httpx.get(f"{BASE}{path}",
                        headers={"Authorization": f"Bearer {API_KEY}"},
                        **kw)
        if res.status_code == 429:
            time.sleep(int(res.headers.get("retry-after", "60")))
            continue
        if 500 <= res.status_code < 600:
            time.sleep(delay)
            delay *= 2
            continue
        res.raise_for_status()
        return res.json()["data"]
    raise RuntimeError("exhausted retries")`}</code>
          </pre>
        </div>

        <h3 className="not-prose mt-6 text-sm font-semibold text-slate-700">
          Go
        </h3>
        <div className="not-prose mt-2 overflow-x-auto rounded-lg bg-slate-900 p-4 text-xs text-slate-100">
          <pre className="font-mono">
            <code>{`package main

import (
    "fmt"
    "io"
    "net/http"
    "os"
    "strconv"
    "time"
)

func call(path string) ([]byte, error) {
    base := "https://api.aec-platform.vn"
    key := os.Getenv("AEC_API_KEY")
    delay := time.Second
    for attempt := 0; attempt < 5; attempt++ {
        req, _ := http.NewRequest("GET", base+path, nil)
        req.Header.Set("Authorization", "Bearer "+key)
        res, err := http.DefaultClient.Do(req)
        if err != nil {
            return nil, err
        }
        defer res.Body.Close()
        if res.StatusCode == 429 {
            secs, _ := strconv.Atoi(res.Header.Get("Retry-After"))
            time.Sleep(time.Duration(secs) * time.Second)
            continue
        }
        if res.StatusCode >= 500 {
            time.Sleep(delay)
            delay *= 2
            continue
        }
        if res.StatusCode >= 400 {
            return nil, fmt.Errorf("status %d", res.StatusCode)
        }
        return io.ReadAll(res.Body)
    }
    return nil, fmt.Errorf("exhausted retries")
}`}</code>
          </pre>
        </div>
      </section>

      {/* ---------- Best practices ---------- */}
      <section>
        <h2 id="best-practices" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          Best practices
        </h2>
        <ul className="space-y-1.5 text-sm text-slate-700">
          <li>
            <strong>Một key cho một mục đích.</strong> CRM-sync và ETL-export là
            hai tích hợp khác nhau → hai key. Revoke một cái không kéo cái kia
            xuống.
          </li>
          <li>
            <strong>Scope tối thiểu.</strong> Read-only ETL pipeline → chỉ{" "}
            <code>projects:read</code>, không cấp <code>:write</code>. Một key bị
            lộ thì hậu quả bị giới hạn.
          </li>
          <li>
            <strong>Đặt expires_at cho key thử nghiệm.</strong> Demo / vendor
            POC nên có hạn 30 ngày. Tránh quên revoke.
          </li>
          <li>
            <strong>Lưu trong vault, không trong repo.</strong> AWS Secrets
            Manager / GCP Secret Manager / Vault — không commit vào git, không
            in ra log.
          </li>
          <li>
            <strong>Theo dõi <code>last_used_at</code>.</strong> Trang{" "}
            <Link href="/settings/api-keys" className="text-blue-600 hover:underline">
              /settings/api-keys
            </Link>{" "}
            hiển thị lần dùng cuối — key không dùng 90 ngày là ứng viên revoke.
          </li>
        </ul>
      </section>

      {/* ---------- Idempotency ---------- */}
      <section>
        <h2 id="idempotency" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          Idempotency
        </h2>
        <p className="text-sm text-slate-700">
          Để retry-safe các write operation (POST / PATCH / DELETE) qua mạng
          không ổn định, gửi header{" "}
          <code className="rounded bg-slate-100 px-1">Idempotency-Key</code>{" "}
          với một UUID v4 mỗi request. Nếu request thất bại do timeout/5xx
          và retry với CÙNG key, server sẽ replay response gốc thay vì chạy
          handler hai lần — không có double-write.
        </p>

        <h3 className="not-prose mt-5 text-sm font-semibold text-slate-700">
          Rules
        </h3>
        <ul className="space-y-1.5 text-sm text-slate-700">
          <li>
            <strong>UUID v4 per logical operation.</strong> Tạo một key mỗi
            khi partner side đã commit ý định "tôi muốn tạo project X" — KHÔNG
            phải mỗi network attempt. Nếu retry do mất kết nối, dùng lại
            cùng key.
          </li>
          <li>
            <strong>Cùng body, cùng key → replay.</strong> Server canonicalise
            body (sort JSON keys) và hash sha256. Nếu hash khớp với bản đã
            cache → trả về response status + body cũ.
          </li>
          <li>
            <strong>Khác body, cùng key → 422.</strong> Như Stripe — phát hiện
            là dấu hiệu partner code đang ghi đè key, hoặc retry sau khi sửa
            payload (logic bug). Không thử đoán nên 422 với marker rõ ràng.
          </li>
          <li>
            <strong>TTL 24 giờ.</strong> Cache giữ response cho 24h. Sau đó
            cùng key được coi là request mới — retry sau 24h sẽ chạy handler
            lại. Phù hợp với đa số network-failure window (ms tới s, không phải
            ngày).
          </li>
          <li>
            <strong>Scope theo api_key_id.</strong> Hai partner gửi cùng UUID
            không xung đột — cache khoá theo (api_key_id, idempotency_key).
          </li>
        </ul>

        <h3 className="not-prose mt-5 text-sm font-semibold text-slate-700">
          Example
        </h3>
        <pre className="overflow-x-auto rounded bg-slate-900 p-4 text-xs text-slate-100">
{`# Generate one UUID before the first attempt:
KEY=$(uuidgen)

# Initial POST (network blip — partner sees timeout):
curl -X POST https://app.aec-platform.vn/api/v1/projects \\
  -H "Authorization: Bearer aec_..." \\
  -H "Idempotency-Key: $KEY" \\
  -H "Content-Type: application/json" \\
  -d '{ "name": "Tower B", "type": "office" }'

# Retry — same KEY, same body. Server replays the cached response
# from the first attempt; the project is created exactly once:
curl -X POST https://app.aec-platform.vn/api/v1/projects \\
  -H "Authorization: Bearer aec_..." \\
  -H "Idempotency-Key: $KEY" \\
  -H "Content-Type: application/json" \\
  -d '{ "name": "Tower B", "type": "office" }'`}
        </pre>

        <p className="mt-4 text-sm text-slate-700">
          Ngôn ngữ TypeScript? SDK <code>@aec/sdk</code> tự động retry trên
          5xx + 429 với exponential backoff — bạn KHÔNG cần generate
          Idempotency-Key thủ công nếu dùng SDK trên hot-path. Generate key
          thủ công khi bạn cần retry vượt cửa sổ retry tự động (vd. background
          job restart sau crash) hoặc khi partner side đang lưu trạng thái
          "operation queued" trong DB của chính họ.
        </p>

        <div className="not-prose mt-5 rounded border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-900">
          <strong>Routes that honor Idempotency-Key.</strong> Áp dụng cho
          mọi POST / PATCH / DELETE trên các router dưới đây. Header trên
          GET hoặc trên các router không liệt kê đều bị bỏ qua (header
          được phép tồn tại; backend không xử lý replay).
          <ul className="mt-2 ml-4 list-disc space-y-0.5">
            <li>
              <code className="rounded bg-emerald-100 px-1">
                /api/v1/api-keys/*
              </code>{" "}
              — mint, revoke, scope updates.
            </li>
            <li>
              <code className="rounded bg-emerald-100 px-1">
                /api/v1/projects/*
              </code>{" "}
              — create, update, delete.
            </li>
            <li>
              <code className="rounded bg-emerald-100 px-1">
                /api/v1/webhooks/*
              </code>{" "}
              — subscription create / update / delete, test-fire,
              redeliver.
            </li>
          </ul>
          <p className="mt-2">
            Routes ngoài danh sách này (vd. <code>/api/v1/defects</code>,{" "}
            <code>/api/v1/rfis</code>) hiện chưa opt-in. Header sẽ được{" "}
            <em>chấp nhận</em> nhưng không bảo vệ retry — gửi key vẫn an
            toàn để chuẩn bị cho khi route đó GA.
          </p>
        </div>
      </section>

      {/* ---------- Sandbox mode ---------- */}
      <section>
        <h2 id="sandbox" className="not-prose mt-0 text-lg font-semibold text-slate-900">
          Sandbox mode (test keys)
        </h2>
        <p className="text-sm text-slate-700">
          Mỗi key có một trường <code>mode</code> với hai giá trị:{" "}
          <code>live</code> (mặc định) và <code>test</code>. Test key truy cập
          một bộ dữ liệu mẫu cố định và <strong>không</strong> ghi vào DB
          thật — đối tác có thể chạy end-to-end mà không cần đụng vào dữ liệu
          production.
        </p>

        {/* Step 1: mint */}
        <h3 className="not-prose mt-5 text-sm font-semibold text-slate-700">
          1. Mint một test key
        </h3>
        <p className="text-sm text-slate-700">
          Trên trang{" "}
          <Link
            href="/settings/api-keys"
            className="text-blue-600 hover:underline"
          >
            /settings/api-keys
          </Link>
          , chọn <strong>Test (sandbox)</strong> trong nhóm "Chế độ" trước khi
          bấm "Tạo key". Hoặc qua API:
        </p>
        <pre className="overflow-x-auto rounded bg-slate-900 p-4 text-xs text-slate-100">
{`curl -X POST https://app.aec-platform.vn/api/v1/api-keys \\
  -H "Authorization: Bearer <admin-jwt>" \\
  -H "X-Org-ID: <org-uuid>" \\
  -H "Content-Type: application/json" \\
  -d '{
    "name": "Partner sandbox",
    "scopes": ["projects:read", "defects:read"],
    "mode": "test"
  }'
# Response includes: "mode": "test", "key": "aec_..." (one-shot plaintext)`}
        </pre>

        {/* Step 2: routing */}
        <h3 className="not-prose mt-5 text-sm font-semibold text-slate-700">
          2. Hit the synthetic-data endpoints
        </h3>
        <p className="text-sm text-slate-700">
          Test key (và live key) đều truy cập được{" "}
          <code>/api/v1/sandbox/*</code> — các endpoint này trả về dữ liệu
          fixture với UUID cố định. Đối tác có thể hardcode các UUID này
          trong integration test:
        </p>
        <pre className="overflow-x-auto rounded bg-slate-900 p-4 text-xs text-slate-100">
{`curl https://app.aec-platform.vn/api/v1/sandbox/projects \\
  -H "Authorization: Bearer aec_<your-test-key>"

# Returns 3 projects with pinned IDs:
#   00000000-0000-0000-0000-000000000001 (construction)
#   00000000-0000-0000-0000-000000000002 (planning)
#   00000000-0000-0000-0000-000000000003 (completed)
# Same UUIDs every time, every deploy. Safe to assert against in
# your CI suite.`}
        </pre>

        {/* Step 3: mutations */}
        <h3 className="not-prose mt-5 text-sm font-semibold text-slate-700">
          3. Mutations return a 202 stub
        </h3>
        <p className="text-sm text-slate-700">
          POST / PATCH / DELETE từ test key được chấp nhận nhưng{" "}
          <strong>không</strong> ghi DB. Phản hồi 202 với marker rõ ràng để
          partner code có thể phân biệt:
        </p>
        <pre className="overflow-x-auto rounded bg-slate-900 p-4 text-xs text-slate-100">
{`# Hypothetical: POST /api/v1/sandbox/projects (test key)
# HTTP 202 Accepted
{
  "data": {
    "status": "accepted_test_mode",
    "action": "create_project",
    "note": "Test-mode keys do not persist mutations. Switch to a
             live key (or POST against a sandbox org) to observe
             DB writes."
  }
}`}
        </pre>

        {/* Step 4: switching to live */}
        <h3 className="not-prose mt-5 text-sm font-semibold text-slate-700">
          4. Switch to live when ready
        </h3>
        <p className="text-sm text-slate-700">
          Khi tích hợp đã verified end-to-end, mint một <em>live</em> key (cùng
          form, chế độ <strong>Live</strong>) và đổi <code>Authorization</code>{" "}
          header. Routes giữ nguyên — kể cả{" "}
          <code>/api/v1/sandbox/*</code> vẫn trả fixture cho live key (cho phép
          partner viết integration test chạy được trong cả prod). Live key gọi
          <code>/api/v1/projects</code> trả về dữ liệu thật của tổ chức.
        </p>

        <div className="not-prose mt-5 rounded border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">
          <strong>⚠ Test ≠ live data isolation.</strong> Test-mode key vẫn có
          thể gọi các route <em>live</em> ({" "}
          <code>/api/v1/projects</code>, etc.) — chúng sẽ trả về dữ liệu thật
          của tổ chức partner. Sandbox là{" "}
          <strong>additive</strong> (cung cấp fixture qua{" "}
          <code>/sandbox/*</code>) chứ không exclusive. Nếu cần cô lập hoàn
          toàn, dùng một sandbox-org riêng (sắp ra mắt).
        </div>
      </section>
    </div>
  );
}


// Source-of-truth mirror of `services.api_keys.SCOPES`. Hand-maintained
// because this is documentation; the compiler can't catch drift.
const SCOPE_DOC: Array<{
  domain: string;
  read: boolean;
  write: boolean;
  writeAction: "write" | "admin";
  description: string;
}> = [
  {
    domain: "projects",
    read: true,
    write: true,
    writeAction: "write",
    description: "Dự án — danh sách, chi tiết, tạo/sửa.",
  },
  {
    domain: "defects",
    read: true,
    write: true,
    writeAction: "write",
    description: "Lỗi (snag list) từ Handover module.",
  },
  {
    domain: "rfis",
    read: true,
    write: true,
    writeAction: "write",
    description: "Yêu cầu làm rõ (Request For Information).",
  },
  {
    domain: "change_orders",
    read: true,
    write: true,
    writeAction: "write",
    description: "Yêu cầu thay đổi thi công.",
  },
  {
    domain: "suppliers",
    read: true,
    write: true,
    writeAction: "write",
    description: "Sổ tay nhà cung cấp.",
  },
  {
    domain: "estimates",
    read: true,
    write: true,
    writeAction: "write",
    description: "Dự toán CostPulse.",
  },
  {
    domain: "webhooks",
    read: false,
    write: true,
    writeAction: "admin",
    description: "Quản lý webhook subscriptions (admin-only).",
  },
  {
    domain: "audit",
    read: true,
    write: false,
    writeAction: "write",
    description: "Nhật ký kiểm tra (read-only).",
  },
  {
    domain: "search",
    read: true,
    write: false,
    writeAction: "write",
    description: "Cross-module search endpoint.",
  },
];
